### ISSUE TITLE
MS Learn Module Update Request: Design a data ingestion strategy for machine learning projects

### ISSUE THREAD

**Issue by Sammybams** [githubpartners/microsoft-learn#102]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

None

### Additional information

- [ ] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [X] Some other request

### Information about the requested update

GRAMMATICAL ERROR
There is a wrong use of an auxiliary verb in the learning content which makes it confusing to straightforward understand.

Unit 2 under 'Identify the data format'

"Based on the source of your data, your data may be stored in a specific format. You need to understand in which format the data currently has and which format you’ll need for your machine learning workloads."

The second sentence should be either "You need to understand which format the data currently has..." or "You need to understand in which format the data currently is..."

**Comment by Chukslord1** [comment]
Hi @Sammybams ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience.

We are currently updating the content to fix this issue. Your patience is greatly appreciated. If you have any further concerns or questions, feel free to let us know.
