### ISSUE TITLE
MS Learn Module Update Request: Code scanning with GitHub CodeQL

### ISSUE THREAD

**Issue by knewbury01** [githubpartners/microsoft-learn#108]
# Which of the MS Learn modules from the dropdown are you submitting an update request?
GitHub administration for GitHub Advanced Security

# Additional information
 - [ ] Fix a broken user experience (broken links, exercise error, etc.)
 - [ ] Update incorrect information
 - [x] Add new content to the module
 - [ ] Some other request
 
# Information about the requested update

1) Unit 5 under the heading - Bulk setup of code scanning-
for a subset of languages , it is now possible to enable code scanning on multiple repos, [from the org level](https://github.blog/changelog/2023-03-20-enable-code-scanning-default-setup-with-codeql-at-the-organization-level-public-beta/)
might want to add mention for this

**Comment by Chukslord1** [comment]
Hi @knewbury01 ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience. Our team is in the process of revising and updating the MS Learn modules for GitHub Advanced Security, and we assure you that your feedback will be incorporated into the upcoming updates.
