### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by luis1184lopez** [githubpartners/microsoft-learn#110]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

Introduction to GitHub

### Additional information

- [ ] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [X] Some other request

### Information about the requested update

In the Github Skills Challenge, in the section to activate github copilot, it sends me a error Extension activation failed: "No access to GitHub Copilot found. You are currently logged in as luis1184lopez, I try to close my session but there is no option to close, I skipped this part of training because I try to create an account in github copilot but says that I need a credit card and I don't have one. Please I will be grateful if I made a mistake or I am in a good way

**Comment by Chukslord1** [comment]
Hello @luis1184lopez ,

Thank you for reaching out with your question regarding GitHub Copilot activation. I understand the importance of resolving this issue, and I'm here to help.

Firstly, I want to clarify that GitHub Copilot does not require a credit card for the free trial. During the free trial period, users can explore GitHub Copilot without the need for any payment information.

However, if while creating an account, you chose to skip the free trial, GitHub Copilot may request credit card information. This is generally for billing purposes in case you decide to continue using GitHub Copilot beyond the free trial period. 

Regarding the error you mentioned during the GitHub Skills Challenge, "Extension activation failed: No access to GitHub Copilot found," I recommend checking a few things:

* Ensure that you have the GitHub Copilot extension installed in your code editor (e.g., Visual Studio Code).
* Confirm that you are signed in with the correct GitHub account in your code editor.
* Verify that you have the right permissions to activate GitHub Copilot by checking your account [settings](https://github.com/settings/copilot) or permissions page on GitHub.

If you continue to experience issues or have further questions, don't hesitate to reach out.
