### ISSUE TITLE
MS Learn Module Update Request: Introducción a GitHub Copilot 

### ISSUE THREAD

**Issue by llonardo798** [githubpartners/microsoft-learn#112]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

None

### Additional information

- [ ] Fix a broken user experience (broken links, exercise error, etc.)
- [X] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

El test del modulo "Introducción a GitHub Copilot" tiene un item que pregunta en donde se puede usar Github Copilot, en el modulo 3 de ese mismo curso (Instalación, configuración y solución de problemas de GitHub Copilot) dice que se admite GitHub.com, Visual Studio Code, Visual Studio, JetBrains y Neovim pero en las opciones de respuesta al seleccionar la que tiene github.com como opción dice que es invalida

**Comment by goosethedev** [comment]
La pregunta es: _What are the supported integrated development environment extensions for GitHub Copilot?_ (¿Cuáles son las extensiones de IDEs que soporta GitHub Copilot?). Se aclara que _GitHub.com_ no requiere una extensión, por lo que aquella opción no aplica como correcta.

**Comment by Chukslord1** [comment]
Hola @llonardo798,

Muchas gracias por presentar este problema. Dado que tus preguntas han sido respondidas y aclaradas, vamos a cerrar este asunto.
