### ISSUE TITLE
MS Learn Module Update Request: Migrate your repository

### ISSUE THREAD

**Issue by hectorsector** [githubpartners/microsoft-learn#71]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

Migrate your repository by using GitHub best practices

### Additional information

- [x] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

This module still references a Learning Lab module. Learning Lab is now [deprecated](https://github.blog/changelog/2022-09-01-deprecating-learning-lab/). 

/cc @learn5git who original reported the issue in https://github.com/skills/.github/issues/243

**Comment by a-a-ron** [comment]
@camihmerhar, can you look into redirecting this link to the deprecated learning lab? I thought we changed this a while ago but looks like this one was missed. Thanks!

Let's discuss this during our sync this week.

**Comment by camihmerhar** [comment]
On it! Will work on this Thursday!

**Comment by mjbear** [comment]
Howdy @camihmerhar 
The [Exercise - Migrating your repository to GitHub](https://learn.microsoft.com/en-us/training/modules/migrate-repository-github/3-migrate-your-repository-to-github) page still links to a [retired/deprecated lab](https://github.com/githubtraining/migrating-your-repository).

If you wouldn't mind, ping me back when the lab content that replaces the retired one is identified.
Thank you! :tada: :dog: :cat: :bird: :grinning: 

**Edit:**
Maybe one module is a newer one and the other is an older one? [0] [1]
I thought I noticed some overlapping content in those two.
For what it's worth [2] refers to [1] and [1] refers to [0] at [3].

Hopefully I kept things straight ... :laughing: 

[0] https://learn.microsoft.com/en-us/training/modules/upload-project-github/
[1] https://learn.microsoft.com/en-us/training/modules/migrate-repository-github/
[2] https://learn.microsoft.com/en-us/training/modules/upload-project-github/5-summary#completion
[3] https://learn.microsoft.com/en-us/training/modules/migrate-repository-github/1-introduction
