### ISSUE TITLE
MS Learn Module Update Request: GitHub administration for GitHub Advanced Security

### ISSUE THREAD

**Issue by CallMeGreg** [githubpartners/microsoft-learn#74]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

GitHub administration for GitHub Advanced Security

### Additional information

- [ ] Fix a broken user experience (broken links, exercise error, etc.)
- [X] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

In `Unit 4: Manage access to GitHub Advanced Security`, the following table should be updated from this:

Type of security alert | Roles and permissions needed
-- | --
Code scanning alerts | Write permission on repository
Secret scanning alerts | Repository administrators and organization owners
Dependabot alerts | Repository administrators and organization owners

and should instead look like this:

Type of security alert | Roles and permissions needed
-- | --
Code scanning alerts | Write permission on repository
Secret scanning alerts | Repository administrators and organization owners
Dependabot alerts | Write permission on repository

In line with a feature change that went live earlier in 2023:
![Screenshot 2023-06-23 at 2 30 27 PM](https://github.com/githubpartners/microsoft-learn/assets/110078080/daf37339-8406-47e6-926d-d2a4efc3fff6)

**Comment by Chukslord1** [comment]
Hi @CallMeGreg ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience. Our team is in the process of revising and updating the MS Learn modules for GitHub Advanced Security, and we assure you that your feedback will be incorporated into the upcoming updates.
