### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by AngusFong88** [githubpartners/microsoft-learn#89]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

None

### Additional information

- [X] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

Introduction to GitHub Copilot , when following the exercise, no further instruction after step 4. Can I assume have completed the exercise ?

**Comment by camihmerhar** [comment]
Howdy @AngusFong88! Thanks for submitting the feedback! Step 4 was the last step in the exercise, if you refresh your repository landing page on GitHub.com itself you should see something similar to the content below. But we'll take your feedback into consideration and potentially add clearer expectations to the intro so people know what to expect. 

<header>



# Code with GitHub Copilot

_GitHub Copilot can help you code by offering autocomplete-style suggestions right in VS Code and Codespaces._

</header>



## Finish

_Congratulations friend, you've completed this course!_

<img src="https://octodex.github.com/images/welcometocat.png" alt=celebrate width=300 align=right>

Here's a recap of all the tasks you completed:

- Set up Copilot inside a Codespace.
- Use Copilot to accept suggested code.
- Use Copilot's hub for alternate suggestions.
- Leverage comments to have Copilot auto-suggest code.

### Additional learning and resources

- [Copilot for Individuals](https://docs.github.com/en/copilot/overview-of-github-copilot/about-github-copilot-for-individuals)
- [Copilot for Business](https://docs.github.com/en/copilot/overview-of-github-copilot/about-github-copilot-for-business)
- [Getting started with Copilot](https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-visual-studio-code)
- [Configure Copilot settings](https://docs.github.com/en/copilot/configuring-github-copilot/configuring-github-copilot-settings-on-githubcom)

### What's next?

- [We'd love to hear what you thought of this course](https://github.com/skills/.github/discussions).
- [Learn another GitHub skill](https://github.com/skills).
- [Read the Get started with GitHub docs](https://docs.github.com/en/get-started).
- To find projects to contribute to, check out [GitHub Explore](https://github.com/explore).

<footer>



---

Get help: [Post in our discussion board](https://github.com/skills/.github/discussions) &bull; [Review the GitHub status page](https://www.githubstatus.com/)

&copy; 2023 GitHub &bull; [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md) &bull; [MIT License](https://gh.io/mit)
