### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by TreyAtC1** [githubpartners/microsoft-learn#90]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

None

### Additional information

- [X] Fix a broken user experience (broken links, exercise error, etc.)
- [X] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

I'm taking hte Cognitive Services challenge on a Mac, as that's what my company uses. The section on CoPilot doesn't note that CoPilot isn't even supported, so I wasted hours installing and poking around to complete the training.
Please update the training to provide information for people who can't use Copilot.

**Comment by camihmerhar** [comment]
Howdy @TreyAtC1 ,

I apologize for your time spent on this exercise. We will definitely update the description to provide more context into utilizing copilot if you have purchased it or utilized the free 30 day trial. 

Let us know if there is anything else we can help with.

Cheers,
Cami
