### ISSUE TITLE
MS Learn Module Update Request: [Introduction to GitHub Co-Pilot]

### ISSUE THREAD

**Issue by UrielEspin** [githubpartners/microsoft-learn#91]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

Introduction to GitHub

### Additional information

- [X] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

Hello there. During this module I kept encountering the same issue and I didn't know how to resolve it. It was usually after step one I saw that when I went to go click on the GitHub extension, it was never never downloaded, which I thought I had resolved by downloading Video Studio Code and connecting my account. After having to manually install it, I notice that it will never proceed me to the next step once I refresh the page. This caused for me to have to click on each step manually and follow along there. I'm not sure if this was something from my end, but if you're able to add more visuals for how to properly set up the Copilot extension or some more images in certain steps to make sure we're following properly, I would think it will be very beneficial.

**Comment by camihmerhar** [comment]
Howdy @UrielEspin,

We appreciate your feedback and I am so sorry for your experience. 

We will definitely take this into account and add a bit more expectation setting in the start of the exercise to hopefully help!

Cheers,
Cami
