### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by HAD223** [githubpartners/microsoft-learn#92]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

Introduction to GitHub

### Additional information

- [X] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

In the module "Code with GitHub Copilor", the exercise Step 2 doesn't execute, because the js. file does not recognise the command "function".

**Comment by camihmerhar** [comment]
Howdy @HAD223,

So sorry you are experiencing this. Do you mind sharing a screen shot of what your experiencing? Also were you able to move onto Step 3 at all?

Cheers,
Cami
