### ISSUE TITLE
Microsoft learn challenge

### ISSUE THREAD

**Issue by Nihaohilaryhao** [githubpartners/microsoft-learn#93]
Hi! 
I hoe you're well. I was trying out the GitHub section of the Machine Learning challenge and stumbled on the step asking the user to type in "Git....js" as I couldn't figure out where the terminal is.

**Comment by camihmerhar** [comment]
Howdy @Nihaohilaryhao!

Thanks for messaging us! Great question, just to follow up to ensure we're on the same page, you're referring to the I[ntroduction to GitHub Copilot](https://learn.microsoft.com/en-us/training/modules/introduction-to-github-copilot/?WT.mc_id=cloudskillschallenge_9fdc6c5c-ea5e-46e4-97d6-2cbfa3603a73) module with the exercise, [Develop with AI powered code suggestions using GitHub Copilot and VS Code](https://learn.microsoft.com/en-us/training/modules/introduction-to-github-copilot/4-exercise) correct?

 If yes, when you're in Codespaces and want to pull up the VS Code terminal go to the hamburger button in the top left corner and it'll provide you a drop down menu and there should be an option to select Terminal and you can select New Terminal and it'll open one within the file you're working on. 
![Screenshot 2023-07-24 at 12 48 49 PM](https://github.com/githubpartners/microsoft-learn/assets/112580737/8127a6f1-6115-41ec-961d-8fc709ede297)

Hope this helps!
