### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by BjoernAuxx** [githubpartners/microsoft-learn#94]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

None

### Additional information

- [X] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

On the Introduction course to GitHub CoPilot the description on how to register correctly for the testing period, especially being forced to provide credit card information prior to being able to actually use the VSCode extension is never mentioned and heavily misleading. Took me quite a while to figure out what was actually wrong.

**Comment by camihmerhar** [comment]
Howdy @BjoernAuxx !

We truly appreciate your feedback! I think this is a great call out, we'll definitely consider making some changes and highlight the expectation of providing credit card information.

Cheers,
Cami
